name: Build & Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Backend image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./docker/Dockerfile.web
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}/web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Trigger Deployment (DEV)
      #   run: |
      #     curl '${{ secrets.INFRA_DEPLOY_DEV_URL }}' \
      #     -H 'CF-Access-Client-Id: ${{ secrets.INFRA_CF_CLIENT_ID }}' \
      #     -H 'CF-Access-Client-Secret: ${{ secrets.INFRA_CF_CLIENT_SECRET }}'